export const TRANSLATION_MAP: any = {
ar: {
    heading: 'عن',
    content: 'اسمي الدكتور ديفيد بارتيكا، وقد قمت بإنشاء بحث W3C. على الرغم من أنني تدربت لعدة سنوات ككيميائي، وحصلت على درجة الدكتوراه من إحدى الجامعات المرموقة ونشرت أكثر من 20 ورقة بحثية، إلا أنني انتقلت إلى تطوير الويب بعد إغلاق آخر شركة هندسية عملت بها (تركز بشكل كبير على الكيمياء) في عام 2011. لقد قمت بهذا التحول الوظيفي من أجل الحصول على وظيفة أفضل وفرص التوازن بين العمل والحياة، وبعد سنوات، أعتقد بشدة أن هذا كان الاختيار الصحيح.<br /><br />&emsp;أشعر أنني في وضع فريد تقريبًا في هذا الصدد يمكنني الآن استخدام مهاراتي العلمية والتحليلية لتطوير مواقع الويب (مثل أداة تحليل CSS الخاصة بي، <a href="https://cssburner.com" target="_blank" rel="noreferrer">CSSBurner</a>) أن الأشخاص الآخرين، أو حتى الفرق، لن يتمكنوا من الإنتاج بكفاءة من حيث التكلفة لأن مثل هذه المواقع تتطلب موظفين متعددين يتمتعون بمجموعات مهارات مختلفة. نقطة نهاية <a href="https://cssburner.com" target="_blank" rel="noreferrer">CSSBurner</a> REST لمجموعة وحدات W3C، والتي تستعلم عن مجموعة شروط المواصفات لكل مستند، يقدم واحدة من هذه الفرص. على الرغم من أن المواصفات وشروطها معروضة وقابلة للبحث باللغة الإنجليزية، إلا أنه تم النظر في الوصول إلى واجهة المستخدم بلغات متعددة (الإنجليزية والإسبانية والفرنسية والإيطالية والألمانية والروسية والكورية واليابانية والصينية والهندية والعربية اعتبارًا من مارس 2024). يعد أمرًا بالغ الأهمية ومتكاملًا لإنشاء غلاف واجهة المستخدم هذا بحيث يمكن لأي مستخدم تقريبًا في جميع أنحاء العالم الوصول إلى هذه المسارد.'
  },
  de: {
    heading: 'Um',
    content: '&emsp;Mein Name ist Dr. David Partyka und ich habe W3C Search erstellt. Obwohl ich mehrere Jahre als Chemiker ausgebildet war, sogar an einer Spitzenuniversität promovierte und über 20 Artikel veröffentlichte, wechselte ich zur Webentwicklung, nachdem das letzte Ingenieurbüro, für das ich gearbeitet hatte (das sich stark auf Chemie konzentrierte), im Jahr 2011 zusammenbrach. Ich habe diesen beruflichen Wechsel vollzogen, um bessere Chancen auf Beschäftigung und Work-Life-Balance zu haben, und Jahre später bin ich fest davon überzeugt, dass dies die richtige Wahl war.<br /><br />&emsp;Ich habe das Gefühl, dass ich mich dabei in einer fast einzigartigen Position befinde Ich kann jetzt meine wissenschaftlichen und analytischen Fähigkeiten nutzen, um Websites zu entwickeln (z. B. mein CSS-Parsing-Tool <a href="https://cssburner.com" target="_blank" rel="noreferrer">CSSBurner</a>). dass andere Personen oder sogar Teams nicht in der Lage wären, kosteneffizient zu produzieren, da für solche Standorte mehrere Mitarbeiter mit unterschiedlichen Fähigkeiten erforderlich wären. Der <a href="https://cssburner.com" target="_blank" rel="noreferrer">CSSBurner</a> REST-Endpunkt für den Satz von W3C-Modulen, der die Sammlung von Spezifikationstemrs pro Dokument abfragt, bietet eine solche Gelegenheit. Obwohl die Spezifikationen und ihre Begriffe auf Englisch präsentiert werden und durchsuchbar sind, wurde ein Zugriff auf die Benutzeroberfläche in mehreren Sprachen (Englisch, Spanisch, Französisch, Italienisch, Deutsch, Russisch, Koreanisch, Japanisch, Chinesisch, Hindi und Arabisch, Stand März 2024) in Betracht gezogen Von größter Bedeutung und integraler Bestandteil der Erstellung dieses UI-Wrappers, sodass nahezu jeder Benutzer auf der ganzen Welt auf diese Glossare zugreifen kann.'
  },
  en: {
    heading: 'About',
    content: '&emsp;My name is Dr. David Partyka, and I created W3C Search. Although I was trained for several years as a chemist, and even earned a PhD from a top university and published over 20 papers, I transitioned into web development after the last engineering company I worked for (heavily-focused on chemistry) folded in 2011. I made this career transition for better employment and work-life balance opportunities, and years later, I wholeheartedly believe this was the correct choice.<br /><br />&emsp;I feel that I am in an almost unique position in that I can now use my scientific and analytical skills to develop websites (such as my CSS parsing tool, <a href="https://cssburner.com" target="_blank" rel="noreferrer">CSSBurner</a>) that other people, or even teams, would not be able to cost-efficiently produce because such sites would require multiple personnel with different skill sets. The <a href="https://cssburner.com" target="_blank" rel="noreferrer">CSSBurner</a> REST endpoint for the set of W3C modules, which queries for the collection of specification temrs per document, presents one such opportunity. Although the specifications and their terms are presented and are searchable in English, user interface access in multiple languages (English, Spanish, French, Italian, German, Russian, Korean, Japanese, Chinese, Hindi, and Arabic as of March 2024) was considered paramount and integral to the creation of this UI wrapper so that these glossaries could be accessed by almost any user around the globe.'
  },
  es: {
    heading: 'Acerca de',
    content: '&emsp;Mi nombre es Dr. David Partyka y creé la W3C Search. Aunque me formé como químico durante varios años, e incluso obtuve un doctorado de una de las mejores universidades y publiqué más de 20 artículos, hice la transición al desarrollo web después de que la última empresa de ingeniería para la que trabajé (muy centrada en la química) cerró en 2011. Hice esta transición profesional para obtener mejores oportunidades de empleo y equilibrio entre vida personal y laboral, y años después, creo sinceramente que esta fue la elección correcta.<br /><br />&emsp;Siento que estoy en una posición casi única en ese sentido. Ahora puedo utilizar mis habilidades científicas y analíticas para desarrollar sitios web (como mi herramienta de análisis de CSS, <a href="https://cssburner.com" target="_blank" rel="noreferrer">CSSBurner</a>). que otras personas, o incluso equipos, no podrían producir de manera rentable porque dichos sitios requerirían mucho personal con diferentes habilidades. El punto final REST <a href="https://cssburner.com" target="_blank" rel="noreferrer">CSSBurner</a> para el conjunto de módulos W3C, que consulta la recopilación de términos de especificación por documento, presenta una de esas oportunidades. Aunque las especificaciones y sus términos se presentan y se pueden buscar en inglés, se consideró el acceso a la interfaz de usuario en varios idiomas (inglés, español, francés, italiano, alemán, ruso, coreano, japonés, chino, hindi y árabe a partir de marzo de 2024). Es primordial e integral para la creación de este contenedor de interfaz de usuario para que casi cualquier usuario en todo el mundo pueda acceder a estos glosarios.'
  },
  fr: {
    heading: 'À propos',
    content: '&emsp;Je m\'appelle Dr David Partyka et j\'ai créé W3C Search. Bien que j\'aie été formé pendant plusieurs années en tant que chimiste, et que j\'ai même obtenu un doctorat dans une grande université et publié plus de 20 articles, je me suis tourné vers le développement Web après la fermeture de la dernière société d\'ingénierie pour laquelle j\'ai travaillé (fortement axée sur la chimie) en 2011. J\'ai fait cette transition de carrière pour de meilleures opportunités d\'emploi et d\'équilibre travail-vie personnelle, et des années plus tard, je crois de tout cœur que c\'était le bon choix.<br /><br />&emsp;Je sens que je suis dans une position presque unique dans ce domaine. Je peux désormais utiliser mes compétences scientifiques et analytiques pour développer des sites Web (comme mon outil d\'analyse CSS, <a href="https://cssburner.com" target="_blank" rel="noreferrer">CSSBurner</a>) que d\'autres personnes, ou même des équipes, ne seraient pas en mesure de produire de manière rentable car de tels sites nécessiteraient plusieurs personnes possédant des compétences différentes. Le point de terminaison REST <a href="https://cssburner.com" target="_blank" rel="noreferrer">CSSBurner</a> pour l\'ensemble des modules du W3C, qui interroge la collection de termes de spécification par document, présente une telle opportunité. Bien que les spécifications et leurs termes soient présentés et consultables en anglais, l\'accès à l\'interface utilisateur dans plusieurs langues (anglais, espagnol, français, italien, allemand, russe, coréen, japonais, chinois, hindi et arabe à partir de mars 2024) a été pris en compte. primordial et essentiel à la création de ce wrapper d\'interface utilisateur afin que ces glossaires puissent être consultés par presque tous les utilisateurs du monde entier.'
  },
  hi: {
    heading: 'के बारे में',
    content: 'मेरा नाम डॉ. डेविड पार्टीका है और मैंने W3C सर्च बनाया है। हालाँकि मुझे एक रसायनज्ञ के रूप में कई वर्षों तक प्रशिक्षित किया गया था, और यहां तक ​​​​कि एक शीर्ष विश्वविद्यालय से पीएचडी भी हासिल की थी और 20 से अधिक शोधपत्र प्रकाशित किए थे, 2011 में जिस आखिरी इंजीनियरिंग कंपनी (रसायन विज्ञान पर अत्यधिक ध्यान केंद्रित) के लिए मैंने काम किया था, उसके बंद होने के बाद मैंने वेब विकास में बदलाव किया। मैंने बेहतर रोजगार और कार्य-जीवन संतुलन के अवसरों के लिए यह करियर परिवर्तन किया, और वर्षों बाद, मैं पूरे दिल से मानता हूं कि यह सही विकल्प था।<br /><br />&emsp;मुझे लगता है कि मैं इसमें लगभग अद्वितीय स्थिति में हूं अब मैं वेबसाइट विकसित करने के लिए अपने वैज्ञानिक और विश्लेषणात्मक कौशल का उपयोग कर सकता हूं (जैसे कि मेरा सीएसएस पार्सिंग टूल, <a href="https://cssburner.com" target="_blank" rel="noreferrer">CSSBurner</a>) अन्य लोग, या यहां तक ​​कि टीमें, लागत-कुशलता से उत्पादन करने में सक्षम नहीं होंगी क्योंकि ऐसी साइटों को विभिन्न कौशल सेट वाले कई कर्मियों की आवश्यकता होगी। W3C मॉड्यूल के सेट के लिए <a href="https://cssburner.com" target="_blank" rel="noreferrer">CSSBurner</a> REST एंडपॉइंट, जो प्रति दस्तावेज़ विनिर्देशन टेम्पलेट्स के संग्रह के लिए क्वेरी करता है, ऐसा ही एक अवसर प्रस्तुत करता है। यद्यपि विनिर्देश और उनकी शर्तें प्रस्तुत की गई हैं और अंग्रेजी में खोज योग्य हैं, कई भाषाओं (मार्च 2024 तक अंग्रेजी, स्पेनिश, फ्रेंच, इतालवी, जर्मन, रूसी, कोरियाई, जापानी, चीनी, हिंदी और अरबी) में यूजर इंटरफेस पहुंच पर विचार किया गया था। इस यूआई रैपर के निर्माण के लिए सर्वोपरि और अभिन्न अंग ताकि इन शब्दावलियों को दुनिया भर में लगभग किसी भी उपयोगकर्ता द्वारा एक्सेस किया जा सके।'
  },
  it: {
    heading: 'Di',
    content: '&emsp;Mi chiamo Dr. David Partyka e ho creato W3C Search. Sebbene abbia studiato per diversi anni come chimico e abbia anche conseguito un dottorato di ricerca in una delle migliori università e pubblicato oltre 20 articoli, sono passato allo sviluppo web dopo che l\'ultima società di ingegneria per cui ho lavorato (fortemente focalizzata sulla chimica) ha chiuso i battenti nel 2011. Ho intrapreso questa transizione professionale per migliori opportunità di lavoro e di equilibrio tra lavoro e vita privata e, anni dopo, credo fermamente che questa sia stata la scelta corretta.<br /><br />&emsp;Sento di trovarmi in una posizione quasi unica in questo Ora posso utilizzare le mie capacità scientifiche e analitiche per sviluppare siti web (come il mio strumento di analisi CSS, <a href="https://cssburner.com" target="_blank" rel="noreferrer">CSSBurner</a>) che altre persone, o addirittura team, non sarebbero in grado di produrre in modo economicamente efficiente perché tali siti richiederebbero più personale con competenze diverse. L\'endpoint REST <a href="https://cssburner.com" target="_blank" rel="noreferrer">CSSBurner</a> per l\'insieme di moduli W3C, che esegue query per la raccolta di termini di specifica per documento, presenta una di queste opportunità. Sebbene le specifiche e i relativi termini siano presentati e siano ricercabili in inglese, è stato preso in considerazione l\'accesso all\'interfaccia utente in più lingue (inglese, spagnolo, francese, italiano, tedesco, russo, coreano, giapponese, cinese, hindi e arabo a partire da marzo 2024). fondamentale e parte integrante della creazione di questo wrapper dell\'interfaccia utente in modo che questi glossari possano essere accessibili da quasi tutti gli utenti in tutto il mondo.'
  },
  ja: {
    heading: 'について',
    content: '私の名前は David Partyka 博士です。W3C Search を作成しました。私は化学者として数年間訓練を受け、一流大学で博士号を取得し、20 本以上の論文を発表しましたが、最後に勤めていたエンジニアリング会社 (化学に重点を置いていた) が 2011 年に倒産した後、Web 開発に移行しました。私はより良い雇用とワークライフバランスの機会を求めてこの転職をしましたが、数年経った今ではこれが正しい選択だったと心から信じています。<br /><br />&emsp;この点において、私はほぼ唯一無二の立場にあると感じています。科学的および分析的スキルを使って Web サイトを開発できるようになりました (CSS 解析ツール <a href="https://cssburner.com" target="_blank" rel="noreferrer">CSSBurner</a> など)そのようなサイトでは、異なるスキルセットを持つ複数の担当者が必要になるため、他の人、またはチームでさえ、コスト効率よく生産することはできません。 W3C モジュールのセットの <a href="https://cssburner.com" target="_blank" rel="noreferrer">CSSBurner</a> REST エンドポイント。ドキュメントごとの仕様項目のコレクションをクエリします。はそのような機会の 1 つを提供します。仕様とその用語は英語で表示され、検索可能ですが、複数の言語 (2024 年 3 月現在、英語、スペイン語、フランス語、イタリア語、ドイツ語、ロシア語、韓国語、日本語、中国語、ヒンディー語、アラビア語) でのユーザー インターフェイス アクセスが検討されました。これは、世界中のほとんどすべてのユーザーがこれらの用語集にアクセスできるようにするために、この UI ラッパーの作成に最も重要かつ不可欠です。'
  },
  ko: {
    heading: '에 대한',
    content: '제 이름은 Dr. David Partyka이고 W3C Search를 만들었습니다. 나는 몇 년 동안 화학자 훈련을 받고 일류 대학에서 박사 학위를 취득하고 20개 이상의 논문을 발표했지만, 2011년에 내가 일했던 마지막 엔지니어링 회사(화학에 중점을 두는)가 문을 닫은 후 웹 개발로 전환했습니다. 저는 더 나은 취업과 일과 삶의 균형을 위해 이 직업 전환을 했고, 몇 년 후 저는 이것이 올바른 선택이었다고 진심으로 믿습니다.<br /><br />&emsp;저는 그 점에서 거의 독특한 위치에 있다고 생각합니다. 이제 과학적이고 분석적인 기술을 사용하여 웹사이트를 개발할 수 있습니다(예: CSS 구문 분석 도구, <a href="https://cssburner.com" target="_blank" rel="noreferrer">CSSBurner</a>) 다른 사람이나 심지어 팀도 비용 효율적으로 생산할 수 없을 것입니다. 그러한 현장에는 서로 다른 기술을 가진 여러 인력이 필요하기 때문입니다. 문서당 사양 항목 모음을 쿼리하는 W3C 모듈 세트에 대한 <a href="https://cssburner.com" target="_blank" rel="noreferrer">CSSBurner</a> REST 엔드포인트는 그러한 기회를 하나 제시합니다. 사양과 해당 용어는 영어로 제시되고 검색 가능하지만, 다국어(2024년 3월 현재 영어, 스페인어, 프랑스어, 이탈리아어, 독일어, 러시아어, 한국어, 일본어, 중국어, 힌디어, 아랍어)로의 사용자 인터페이스 액세스가 고려되었습니다. 전 세계 거의 모든 사용자가 이러한 용어집에 액세스할 수 있도록 이 UI 래퍼를 만드는 데 가장 중요하고 필수적인 것입니다.'
  },
  ru: {
    heading: 'О',
    content: '&emsp;Меня зовут доктор Дэвид Партика, и я создал W3C Search. Хотя я несколько лет учился на химика, даже получил докторскую степень в ведущем университете и опубликовал более 20 статей, я перешел в веб-разработку после того, как последняя инжиниринговая компания, в которой я работал (специально ориентированная на химию), закрылась в 2011 году. Я совершил этот карьерный переход ради лучших возможностей трудоустройства и обеспечения баланса между работой и личной жизнью, и годы спустя я искренне верю, что это был правильный выбор.<br /><br />&emsp;Я чувствую, что нахожусь в почти уникальном положении в этом вопросе. Теперь я могу использовать свои научные и аналитические навыки для разработки веб-сайтов (например, с помощью инструмента анализа CSS <a href="https://cssburner.com" target="_blank" rel="noreferrer">CSSBurner</a>). что другие люди или даже команды не смогут производить экономически эффективно, потому что на таких объектах потребуется несколько сотрудников с разными наборами навыков. Конечная точка REST <a href="https://cssburner.com" target="_blank" rel="noreferrer">CSSBurner</a> для набора модулей W3C, которая запрашивает сбор спецификаций для каждого документа, представляет одну из таких возможностей. Хотя спецификации и их термины представлены и доступны для поиска на английском языке, рассматривался доступ к пользовательскому интерфейсу на нескольких языках (английский, испанский, французский, итальянский, немецкий, русский, корейский, японский, китайский, хинди и арабский по состоянию на март 2024 г.). имеет первостепенное значение и является неотъемлемой частью создания этой оболочки пользовательского интерфейса, чтобы эти глоссарии могли быть доступны практически любому пользователю по всему миру.'
  },
  zh: {
    heading: '關於',
    content: '我的名字是 David Partyka 博士，我創建了 W3C 搜尋。儘管我接受了多年的化學家培訓，甚至從頂尖大學獲得了博士學位，並發表了20 多篇論文，但在我工作的最後一家工程公司（主要專注於化學）於2011 年倒閉後，我轉向了Web 開發。我進行職業轉型是為了獲得更好的就業和工作與生活平衡的機會，多年後，我全心全意地相信這是正確的選擇。<br /><br />&emsp;我覺得我在這方面幾乎處於獨特的位置我現在可以利用我的科學和分析技能來開發網站（例如我的CSS 解析工具<a href="https://cssburner.com" target="_blank" rel="noreferrer" >CSSBurner</a>）其他人甚至團隊將無法經濟高效地進行生產，因為此類站點需要多名具有不同技能的人員。 W3C 模組集的 <a href="https://cssburner.com" target="_blank" rel="noreferrer">CSSBurner</a> REST 端點，用於查詢每個文件的規範術語集合，就提供了這樣一個機會。儘管規範及其術語以英語呈現並可搜索，但考慮了多種語言的使用者介面存取（英語、西班牙語、法語、義大利語、德語、俄語、韓語、日語、中文、印地語和阿拉伯語，截至2024 年3 月）對於創建此 UI 包裝器至關重要且不可或缺，以便全球幾乎任何用戶都可以存取這些術語表。'
  }
};

export default TRANSLATION_MAP;
